front:
  name: "frontend"
  port: 80
  image:
    name: "localhost:5000/game-frontend"
    tag: "latest"
  replicaCount: 1
back:
  name: "backend"
  port: 4444
  image:
    name: "localhost:5000/game-backend"
    tag: "latest"
  replicaCount: 1
image:
  secrets:
tls:
  enabled: false
prometheus:
  metrics: false
gitlab:
  app:
  env:
  envName:
  envURL:
