stages:
  - build
  - review
  - staging

build-back:
  image: maven:3.6.2-jdk-11
  stage: build
  tags:
    - build
  script:
    - cd game-backend
    - mvn clean package
  artifacts:
    paths:
      - game-backend/target/game-backend-1.3.0.jar
    expire_in: 1 hour

build-front:
  image: node:14.17.0
  stage: build
  tags:
    - build
  cache:
    paths:
      - node_modules/
  script:
    - cd game-frontend
    - npm install
    - npm run ng build --prod --build-optimizer

review:
  stage: review
  tags:
    - review
  script:
    - echo "review"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN 
  only:
    - branches
  except:
    - master

staging:
  stage: staging
  tags:
    - staging
  script:
    - echo "staging"
  environment:
    name: staging
    url: http://staging.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - master
