stages:
  - build
  - check
  - deploy

pull-images:
  stage: .pre
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull maven:3.8-openjdk-11 && docker tag maven:3.8-openjdk-11 $CI_REGISTRY/guillaumejchauveau/cpoo-project/maven:3.8-openjdk-11
    - docker build -t $CI_REGISTRY/guillaumejchauveau/cpoo-project/node-chrome:16 node-chrome
    - docker push $CI_REGISTRY/guillaumejchauveau/cpoo-project/maven:3.8-openjdk-11
    - docker push $CI_REGISTRY/guillaumejchauveau/cpoo-project/node-chrome:16
  when: manual

back:build:
  stage: build
  image: $CI_REGISTRY/guillaumejchauveau/cpoo-project/maven:3.8-openjdk-11
  tags:
    - build
  before_script:
    - cd game-backend
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository compile
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository/
  artifacts:
    paths:
      - game-backend/target/*.jar
    expire_in: 1 hour

front:build:
  stage: build
  image: $CI_REGISTRY/guillaumejchauveau/cpoo-project/node-chrome:16
  tags:
    - build
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/
  before_script:
    - cd game-frontend
  script:
    - npm install
    - npm run ng build -- --prod --build-optimizer

back:test:
  stage: check
  image: $CI_REGISTRY/guillaumejchauveau/cpoo-project/maven:3.8-openjdk-11
  tags:
    - check
  needs:
    - back:build
  before_script:
    - cd game-backend
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository test
  artifacts:
    reports:
      junit:
        - game-backend/target/surefire-reports/TEST-*.xml
      # TODO: coverage
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository/
    policy: pull

front:test:
  stage: check
  image: $CI_REGISTRY/guillaumejchauveau/cpoo-project/node-chrome:16
  tags:
    - check
  needs:
    - front:build
  before_script:
    - cd game-frontend
    - export CHROME_BIN=
  script:
    - npm run ng test -- --code-coverage --watch=false --browsers=GitlabHeadlessChrome --reporters=junit
    - ls -la
  coverage: '/Statements\s+:\s\d+.\d+%/'
  artifacts:
    reports:
      junit:
        - game-frontend/tests/junit-test-results.xml
      cobertura:
        - game-frontend/coverage/cobertura.txt
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/
    policy: pull

#TODO: Linting

review:
  stage: deploy
  tags:
    - review
  script:
    - echo "review"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - branches
  except:
    - master

staging:
  stage: deploy
  tags:
    - staging
  script:
    - echo "staging"
  environment:
    name: staging
    url: http://staging.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - master
