front:build:
  stage: build
  image: $NODE_CHROME_IMAGE
  tags:
    - ci
  before_script:
    - cd game-frontend
    - npm install
  script:
    - npm run ng build -- --prod --build-optimizer
  artifacts:
    paths:
      - game-frontend/dist/game-frontend/*
    expire_in: 1 hour
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/

front:test:
  stage: check
  image: $NODE_CHROME_IMAGE
  tags:
    - ci
  needs:
    - front:build
  before_script:
    - cd game-frontend
    - npm install
  script:
    - |
      npm run ng test -- \
      --watch=false --code-coverage --reporters=progress,junit \
      --browsers=GitlabHeadlessChrome
  artifacts:
    when: always
    reports:
      junit: game-frontend/tests/junit-test-results.xml
      cobertura: game-frontend/coverage/cobertura.xml
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/

front:lint:
  stage: check
  image: $NODE_CHROME_IMAGE
  tags:
    - ci
  needs:
    - front:build
  before_script:
    - cd game-frontend
    - npm install
  script:
    - npm run --silent ng lint -- --format=checkstyle > tslint-report.xml
  artifacts:
    when: always
    paths:
      - game-frontend/tslint-report.xml
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/

front:report_lint:
  stage: report
  image: $CHECKSTYLE_REPORT_CODECLIMATE_IMAGE
  tags:
    - ci
  needs:
    - front:lint
  variables:
    GIT_STRATEGY: none
  when: always
  script:
    - cd game-frontend
    - cat tslint-report.xml | python /opt/checkstyle-report-codeclimate.py > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: game-frontend/gl-code-quality-report.json
