include: /.gitlab-ci.common.yml

front:build:
  stage: build
  image: $NODE_CHROME_IMAGE
  tags:
    - ci
  before_script:
    - cd game-frontend
  script:
    - npm install
    - npm run ng build -- --prod --build-optimizer
  artifacts:
    paths:
      - game-frontend/dist/game-frontend/*
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/

front:test:
  stage: check
  image: $NODE_CHROME_IMAGE
  tags:
    - ci
  needs:
    - front:build
  before_script:
    - cd game-frontend
  script:
    - npm run ng test -- --code-coverage --watch=false --browsers=GitlabHeadlessChrome --reporters=junit
  artifacts:
    paths:
      - game-frontend/tests/junit-test-results.xml
      - game-frontend/coverage/cobertura.xml
  cache:
    key:
      files:
        - game-frontend/package-lock.json
    paths:
      - game-frontend/node_modules/
    policy: pull

front:report:
  stage: report
  tags:
    - ci
  needs:
    - front:test
  variables:
    GIT_STRATEGY: none
  script:
    - cd game-frontend
  artifacts:
    reports:
      junit: game-frontend/tests/junit-test-results.xml
      cobertura: game-frontend/coverage/cobertura.xml

front:publish:
  <<: *registry-job
  stage: publish
  needs:
    - job: front:test
      artifacts: false
    - job: front:build
      artifacts: true
  script:
    - docker build --pull -t "$FRONT_IMAGE${tag}" game-frontend
    - docker push "$FRONT_IMAGE${tag}"
