back:build:
  stage: build
  image: $MAVEN_IMAGE
  tags:
    - ci
  before_script:
    - cd game-backend
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DskipTests -Dmaven.test.skip=true clean package
  artifacts:
    paths:
      - game-backend/target/*.jar
    expire_in: 1 hour
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository/

back:verify:
  stage: check
  image: $MAVEN_IMAGE
  tags:
    - ci
  needs:
    - back:build
  before_script:
    - cd game-backend
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository verify
  artifacts:
    when: always
    reports:
      junit: game-backend/target/surefire-reports/TEST-*.xml
    paths:
      - game-backend/target/site/jacoco/jacoco.xml
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository/
    policy: pull

back:integration_test:
  stage: check
  image: $OPENJDK_SCHEMATHESIS_IMAGE
  tags:
    - ci
  needs:
    - back:build
    - api:build
  variables:
    GIT_STRATEGY: none
  script:
    - java -cp game-backend/target/game-backend-* game.Main http://0.0.0.0:4444/ &
    - sleep 2
    - |
      schemathesis run \
      --checks all \
      --base-url=http://localhost:4444 \
      --junit-xml=schemathesis.xml \
      ./openapi.json
  artifacts:
    when: always
    reports:
      junit: schemathesis.xml

back:report:
  stage: report
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  tags:
    - ci
  needs:
    - back:verify
  when: always
  before_script:
    - cd game-backend
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java/ > target/site/cobertura.xml
  artifacts:
    reports:
      cobertura: game-backend/target/site/cobertura.xml
