build-back:
  image: maven:3.6.2-jdk-11
  stage: build
  script:
    - cd game-backend
    - mvn clean package
  artifacts:
    paths:
      - game-backend/target/game-backend-1.3.0.jar
    expire_in: 1 hour

build-front:
  image: node:14.17.0
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - cd game-frontend
    - npm install
    - npm run ng build --prod --build-optimizer

