apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "appname" . }}-backend
  annotations:
    {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
    {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
  labels:
{{ include "sharedlabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      release: {{ .Release.Name }}
      tier: backend
  replicas: {{ .Values.front.replicaCount }}
  template:
    metadata:
      annotations:
        {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
        {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
      labels:
{{ include "sharedlabels" . | indent 8 }}
        tier: backend
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "imagename" .Values.back.image }}
          imagePullPolicy: Always
          ports:
            - name: "{{ .Values.back.name }}"
              containerPort: {{ .Values.back.port }}
          livenessProbe:
            httpGet:
              path: "/swagger.json"
              scheme: "HTTP"
              port: {{ .Values.back.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: "/swagger.json"
              scheme: "HTTP"
              port: {{ .Values.back.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-backend
  annotations:
{{- if .Values.prometheus.metrics }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.back.port }}"
{{- end }}
  labels:
{{ include "sharedlabels" . | indent 4 }}
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.back.port }}
    targetPort: {{ .Values.back.port }}
    protocol: TCP
    name: {{ .Values.back.name }}
  selector:
    app: {{ template "appname" . }}
    tier: backend
