apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "sharedlabels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.tls.enabled }}
    cert-manager.io/issuer: "letsencrypt-prod"
    {{- end }}
    {{- if .Values.prometheus.metrics }}
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /metrics {
          deny all;
      }
    {{- end }}
spec:
  {{- $baseHost := (default "http://localhost" .Values.gitlab.envURL) | trimPrefix "http://" |  trimPrefix "https://" | trimSuffix "/" | trim -}}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ $baseHost }}
      secretName: letsencrypt-prod
    - hosts:
        - api.{{ $baseHost }}
      secretName: api-letsencrypt-prod
  {{- end }}
  rules:
    - host: {{ $baseHost }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ template "fullname" . }}-frontend
                port:
                  number: {{ .Values.front.port }}
    - host: api.{{ $baseHost }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ template "fullname" . }}-backend
                port:
                  number: {{ .Values.back.port }}
---
{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: guillaume.chauveau@insa-rennes.fr
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
